### ISSUE TITLE
No networks found in the project when adding image

### ISSUE THREAD

**Issue by mxpv** [JetBrains/teamcity-google-agent#4]
Hey. I can't add an image because of "No networks found in the project" error.

<img width="620" alt="screen shot 2017-07-07 at 4 04 09 pm" src="https://user-images.githubusercontent.com/865334/27979862-fbffacf6-632d-11e7-8f1a-35f1778cf27f.png">

I have two networks in my GCP account (including default one).
TC server is hosted on GCE instance.

There is also one suspicious thing in `teamcity-clouds.log `

```
[2017-07-07 20:57:22,310]   WARN [nio-8111-exec-4] - .beans.CloudTabFormFactoryImpl - Can't find projectId by projectExtId '' 
[2017-07-07 22:34:40,464]   WARN [io-8111-exec-11] - .beans.CloudTabFormFactoryImpl - Can't find projectId by projectExtId '' 
``` 

Could you suggest a workaround? 
Thanks.

**Comment by dtretyakov** [comment]
Hi @mxpv, it could be caused by lack of permissions to list networks for this service account.
If Resource Manager API is disabled in your project, please [enable it](https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview) and then update the Google cloud profile page to check the reported errors.

If it will report that you need a `compute.networks.list` please grant in IAM `Compute Network Viewer` role for your service account, but usually granting `Compute Instance Admin (v1)` role [is enough](https://blog.jetbrains.com/teamcity/2017/06/run-teamcity-ci-builds-in-google-cloud/).

If it does not help could you please check what result returns the [compute.networks.list](https://developers.google.com/apis-explorer/#p/compute/v1/compute.networks.list) method for this project?

**Comment by mxpv** [comment]
Thanks!
